---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - config/initializers/simple_form_bootstrap.rb # generated
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  haml-lint:
    enabled: true
    channel: beta
  reek:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-48
ratings:
  paths:
  - "**.erb"
  - "**.haml"
  - "**.js"
  - "**.rb"
